package(
    default_visibility = ["//visibility:public"],
)

cc_library(
    name = "image_frame",
    srcs = ["image_frame.cc"],
    hdrs = ["image_frame.h"],
    deps = [
        "//mediapipe/apis:common",
        "//mediapipe/framework/formats:image_frame",
    ],
    alwayslink = True,
)
