cc_binary(
    name = "mediapipe_c",
    deps = [
        "//mediapipe/calculators/core:pass_through_calculator",
        "//mediapipe/apis/framework:calculator_graph",
    ],
    visibility = None,
    linkshared = True,
)
